"""add toolbar_state and user.created_at

Revision ID: d8e43b129ddd
Revises: 5276e6feaee0
Create Date: 2026-09-18 21:21:37.830397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e43b129ddd'
down_revision = '5276e6feaee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prototype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toolbar_state', sa.String(length=20), server_default='expanded', nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('prototype', schema=None) as batch_op:
        batch_op.drop_column('toolbar_state')

    # ### end Alembic commands ###
